### ISSUE TITLE
Deskewing: Set Background to Min/Mode Value

### ISSUE THREAD

**Issue by felixwaeldchen** [tlambert03/LLSpy#10]
This is not an issue but rather a proposal.

I routinely use the deskewed stack for further analysis. With background set to 0, the moving window of actual data creates a hard edge that causes many issues for e.g. edge detecion or even single molecule localization.

It would be awesome to have an option to fill the background with a value other than 0. My suggestion would be to just use the value that can be selected in the preprocessing tab (fixed or mode value).

Best,
Felix

**Comment by tlambert03** [comment]
i can probably do that pretty easily... will keep this open until added

**Comment by tlambert03** [comment]
added manual pad value entry ... but haven't linked it to the preprocessing tab yet...

**Comment by tlambert03** [comment]
closing as this project is in maintenance mode, likely will not add new features
