### ISSUE TITLE
bug affecting file names containing >7 digits of the msec field

### ISSUE THREAD

**Issue by linshaova** [tlambert03/LLSpy#14]
First I found that registration fails for files after a certain time point. Then I realized the difference in those files are that their file names contain >7 digits in the `msec` field. And I traced it down to `parse.py` where a `filename_pattern` is defined. So I changed line 40 from
`	_(?P<reltime>\d{7})msec 	# 7 digits after _ and before msec`
to
`	_(?P<reltime>\d{7,8})msec 	# 7 or 8 digits after _ and before msec`

And this seems to have done the trick. Maybe we should just change it to {7,10} just in case there would be some extra long time lapsed images. I'm surprised nobody else encountered this issue yet!

I'm also surprised why the decon part is not affected by the filename_pattern bug (i.e., why it only affects the registration phase). You probably can think of a quick answer.

lin

**Comment by tlambert03** [comment]
interesting, thanks for the heads up. I guess I hadn't come across that case yet and didn't know what Dan's software did with the filename in that case.  Thanks!
