### ISSUE TITLE
Minor Issues in v0.4

### ISSUE THREAD

**Issue by bscott711** [tlambert03/LLSpy#15]
Hey Talley,

First off, great work on this! 
Following the update, the spimagine plugin works on my windows machine, so thank you!

I noticed three minor issues pop up.

1) Following rotation, the dz value is not being upsampled in the metadata, and is kept at the deskewed value, for a typical 500 nm stage step size, it is ~250 nm following deskewing, following rotation it should be ~100 nm. 

2) The metadata for the time interval in the MIPs was lost in this version, when loading into fiji it just has it listed as 0.

3) In ditch_partial_tiffs (llsdir.py line 725), the threshold of 1000 is problematic, because we have some images that are the same size but differ slightly in size for some weird reason even though they are straight off the camera. (164,756 KB vs 164,759 KB) . It may be better to use a threshold based on whether there is an image missing: thresh=ny*nx*bitDepth/8. For a 768x768 image that is 1179648

Thanks again,
-Brandon

**Comment by tlambert03** [comment]
Great catches, thanks!

The metadata for rotation will require a change in cudaDeconv itself, and can be done and distributed as an update to llspy_extra. 
For the MIPs, you're talking about the combo-MIP generated by LLSpy right?  I'll figure out where that went...
Yeah, ditch_partial_tiffs is all-around problematic!  That was an early idea that I never returned to to improve. I like your idea and will implement something like that, in addition to, perhaps, just making the whole check optional.

**Comment by bscott711** [comment]
Sounds good, and yes I was talking about the combo-mip. (Super helpful!)

There seems to be a major bottleneck in writing the file to disk following deconvolution.
It is taking ~1 minute to process a timepoint, and 56 seconds of that is writing the file to disk.
For a comparison, in version 0.3.9, the same data and settings takes 4 seconds, with 2 seconds of writing.

**Comment by tlambert03** [comment]
oh no...  that's not good news at all.  What I can say is that multi-threaded IO got introduced into the cudaDeconv code, between the version of cudaDeconv that was used in 0.3.9 and the current one. 

Can you tell me what OS version and GPU you're using?  Also, does it matter whether you uncheck saveDeskewedRaw or uncheck all of the MIPs options?

 Pinging @linshaova and @dmilkie ...

**Comment by bscott711** [comment]
![image](https://user-images.githubusercontent.com/40175801/52883079-f9bde200-3126-11e9-924b-55bb6f15e54f.png)

I modified the llspy v.0.3.9 to make use of Lin's last cudaDeconv from ~Jul of last year, and that one is the comparison I am making. I don't have saveDeskewedRaw checked, I will test the MIPs option.

**Comment by tlambert03** [comment]
Thanks.  Can you print the output from `cudaDeconv -h` for the version that works fine?

**Comment by bscott711** [comment]
![image](https://user-images.githubusercontent.com/40175801/52883507-6edde700-3128-11e9-982b-b34b6040ecd3.png)

**Comment by tlambert03** [comment]
just sent you a single-threaded version to test.  lemme know if it changes anything

**Comment by dmilkie** [comment]
Here is the performance of the latest cudaDeconv that I compiled at the beginning of this month using the latest libraries (Feburary 2019): 
**9.58 seconds**
![image](https://user-images.githubusercontent.com/17623663/52886452-4e228b00-3142-11e9-8004-e2b6e6c6721b.png)

Here is the performance of the April 2017 version:
**10.54 seconds**
![image](https://user-images.githubusercontent.com/17623663/52886620-de60d000-3142-11e9-9ece-455b7891dbbd.png)

**Comment by tlambert03** [comment]
Fixed it.  Something happened between CImg.h version 1.7.9 and version 2.0.0 that makes cudaDeconv hang on the last file for some reason (I was using 2.3.3, the regular cudaDeconv uses 1.5.8).  I wasn't able to figure out exactly what the problematic change was in CImg, but in any case, moving to 1.7.9 gives me all of the metadata interface I need, without the slowdown.  I'll update llspy_extra soon.

**Comment by tlambert03** [comment]
issue 1 and the slowdown is fixed in llspy_extra_0.4.1.   issues 2 and 3 are fixed in 52c42c9 and bc4563e respectively.
