### ISSUE TITLE
Request: example dataset

### ISSUE THREAD

**Issue by JeremyPike** [tlambert03/LLSpy#23]
Hi

We are planning to write subroutines such that we can use LLSpy on data acquired from a 3i LLS. For comparison it would be great to have a small example data-set acquired with the Lattice Scope LabView software including PSFs and settings files and with the expected directory structure. Is this something you could provide please?

Thank you
Jeremy

**Comment by tlambert03** [comment]
here's a sample dataset, some OTFs, and an example camera params file:
https://www.dropbox.com/s/y10uio5d3lk5ezq/llspy%20test%20data.zip?dl=0

**Comment by tlambert03** [comment]
see also: https://llspy.readthedocs.io/en/latest/main.html#data-structure-assumptions

**Comment by JeremyPike** [comment]
Great, thank you!
