### ISSUE TITLE
Anaconda Prompt Update Command Not Working

### ISSUE THREAD

**Issue by kdmarchuk** [tlambert03/LLSpy#29]
Hi Talley, 

I'm on version of 3.7 of llspy (internet access fight with IT). 

Running `conda update -c talley llspy` does not update the package. Instead I'm told "All requested packages already installed"

Maybe my version is too old to update? Do you suggest a reinstall?

Thanks

**Comment by tlambert03** [comment]
probably some version conflict with another dependency in your environment, and maybe it thinks that 0.3.7 is as high as it can go (can't remember what the deps were back then).  Yes, create a new environment with a fresh `conda create -n newenv -c conda-forge -c talley llspy`
