### ISSUE TITLE
GPU cannot be recognized

### ISSUE THREAD

**Issue by yemaopt** [tlambert03/LLSpy#30]
Hi Talley!
Sorry that I currently suffer the problem that the GPU I used cannot be recognized by CUDA, shown as attached 
![Screen Shot 2020-04-19 at 12 44 50 PM](https://user-images.githubusercontent.com/50851106/79694171-c0a66380-823c-11ea-920b-8943154b3bc7.png)
Before I didn't have this problem, until I installed the cudatoolkit 9.1 and MS2015 for other purpose on matlab codes. I reinstall the llspy and it doesn't help. 
Could you give me some hint how I can solve it? I guess the cudatool kit version can be an issue.
![Screen Shot 2020-04-19 at 10 57 15 AM](https://user-images.githubusercontent.com/50851106/79694167-b1271a80-823c-11ea-8dbc-319509ef0d71.png)

Thank you so much for your help!

**Comment by tlambert03** [comment]
does running cudadeconv from the command line give you any useful errors?

**Comment by yemaopt** [comment]
Hi Talley!
Thank you so much for your hint! Yes, it shows the driver version is older, and thus I updated the NVIDIA driver, and recompile the MEX for the other matlab code, so that both work well finally.
Many thanks for your help!
Ye

**Comment by tlambert03** [comment]
great!  glad you were able to figure it out!
