### ISSUE TITLE
No CUDA-capable GPUs detected

### ISSUE THREAD

**Issue by XarlesSta** [tlambert03/LLSpy#31]
Hi Talley. I have been running the LLSpy software without a problem for months. Today, when I tried to run the deconvolution using the GUI, I got the error "No CUDA-capable GPUs detected" in the Config tab. I reinstalled the llsenv and updated channels but it did not work. Any suggestions?

Windows 10
NVIDIA GeForce GTX 960
Pyhton 3.6.10
Driver version 388.13
DirectX runtime version 11.0

**Comment by tlambert03** [comment]
can you give me any hints about what I might have changed in the meantime?  new GPU driver?  new cuda driver?  new llspy version?  I can't think of any reason why it would work one day and not the next without changing something about the environment.

one thing that often helps to debug is to try to run cudadeconv directly from the command line.  that might give you an error you can follow up on
