### ISSUE TITLE
Illegal Memory Access

### ISSUE THREAD

**Issue by parthnatekar** [tlambert03/LLSpy#37]
Hi, I'm getting this same error as #21 (albeit with a different error code).

I find that I can only process images below a certain size. I'm using a 24GB RTX 3090, so I doubt that I'm running out of memory.

The images I'm processing are about 512x1024x200 (16 bit).

![Screenshot from 2022-05-16 11-42-21](https://user-images.githubusercontent.com/33252453/168661021-6d0f8511-aa31-4a47-a6d6-28c73f9b994b.png)

**Comment by parthnatekar** [comment]
Hi @tlambert03 any help with this?

**Comment by linshaova** [comment]
Hi Parth, could you share the dataset and PSF or OTF used when this error occurred? I might be able to help. Thanks!

lin

**Comment by tlambert03** [comment]
no reply from original poster, so will close
